alias asdf="setxkbmap de neo"
alias uiae="setxkbmap de"
alias lsold="command ls -rtlh *(D.Om[1,10])"
alias cwd="pwd | clipcopy"
alias dc="sudo docker compose"
alias dce="sudo docker compose exec"
alias dclog="sudo docker compose logs --tail 50 -f"
alias d="sudo docker"
alias drun="sudo docker run -it --rm"
alias gw="findReverseInGit gradlew"
eval $(thefuck --alias) # insert the 'fuck' alias
alias tg="terragrunt"
alias ls="exa"
alias la="exa -la"
alias cz="chezmoi"
alias gcli="findReverseInGit gcli"
